Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -1,8 +1,7 @@
 name: C++ CI
 
-on:
-  workflow_dispatch:
-  
+on: [push]
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -18,6 +17,14 @@ jobs:
         source /opt/rh/devtoolset-8/enable
         gcc --version
         g++ --version
+
+    - name: Create and Verify Build Directory
+      run: |
+        mkdir -p build
+        if [ ! -d "build" ]; then
+          echo "Build directory not found!"
+          exit 1
+        fi
 
     - name: Configure CMake
       run: |
